employeeName=input("Enter the Employee Name : \n")
employeeSalary=float(input("Enter the Employee Salary : \n"))
employeePhone=int(input("Enter the Employee Phone Number : \t"))
print(employeeName,employeeSalary,employeePhone)
print(type(employeeName),type(employeeSalary),type(employeePhone))