mystr='guvi is the Best Training Platform'
print("Lowercase:",mystr.lower())
print("Uppercase:",mystr.upper())
print("Capitalize:",mystr.capitalize())
print("Index:",mystr.index('B'))
print("Index:",mystr.index('Platform'))
print("Index:",mystr.index('i'))
# print("Index:",mystr.index('ark'))
print("Find:",mystr.index('B'))
print("Find:",mystr.index('Platform'))
print("Find:",mystr.find('i'))
print("Find:",mystr.find('ark'))
print("Replace:",mystr.replace("Platform","Institute"))
# mystr=mystr.replace("Platform","Institute")
print("Original String: ",mystr)
print("StartsWith:",mystr.startswith("guvi"))
print("Endswith:",mystr.endswith("orm"))
print("length of string:",len(mystr))
print("isApla:",mystr.isalpha())
print("isAplaNumeric:",mystr.isalnum())